#spring.application.name=spring_data_jpa
#spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/jpatest?serverTimezone=Asia/Seoul
#spring.datasource.hikari.username=root
#spring.datasource.hikari.password=1234
#spring.datasource.hikari.maximum-pool-size=3
#  server.servlet.session.timeout=30m
#  server.servlet.session.tracking-modes=cookie

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/jpashop?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false





