#spring.application.name=spring_data_jpa
#spring.datasource.driver-class-name=com.cj.
#spring.datasource.url=jdbc:mysql
#spring.datasource.user=root
#spring.datasource.password=1234

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/jpatest?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true

